### ISSUE TITLE
You can just push whole miku device repo of mona to your new branch.

### ISSUE THREAD

**Issue by AmeChanRain** [iamr0s/android_device_tree_xiaomi_mona#1]
But don't kang it. You lost all commit history, respect all contributors plz.

**Comment by iamr0s** [comment]
just for test github action build, will not release.

**Comment by AmeChanRain** [comment]
I mean, you can push it with full history(keeping the original commit history is a sign of respect for all contributors, and it will let us know what happened to this repo), and then you can do whatever you want. : )

**Comment by iamr0s** [comment]
I mean, I just test Github Action and forget delete this branch.
> Deleted.

**Comment by AmeChanRain** [comment]
Sorry for annoying, have a nice day. :3
